"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Film, Search, Play, SlidersHorizontal, Bookmark, BookmarkCheck, History, Upload, Database, LoaderCircle, CircleAlert, X, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Tabs,TabsList,TabsTrigger,TabsContent } from "@/components/ui/tabs";
import { Dialog,DialogContent,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { Switch } from "@/components/ui/switch";
import { Skeleton } from "@/components/ui/skeleton";
import { Empty,EmptyTitle,EmptyDescription } from "@/components/ui/empty";
import { Toaster } from "@/components/ui/sonner";
import { MoviePlayer } from "./player";
import { demoMovies } from "@/lib/cinema/catalog";
import { matches,mergeMovies,parseCatalog } from "@/lib/cinema/normalize";
import type {Movie,SearchResult,SourceStatus,WatchRecord} from "@/lib/cinema/types";

const keys={favorites:"jiaying.v1.favorites",history:"jiaying.v1.history",catalog:"jiaying.v1.catalog"};
function load<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)??"null")??fallback;}catch{return fallback;}}
function persist(key:string,value:unknown){try{localStorage.setItem(key,JSON.stringify(value));}catch{toast.error("本设备存储空间不足，暂时无法保存记录");}}
function time(seconds:number){const whole=Math.floor(seconds);return `${Math.floor(whole/60)}:${String(whole%60).padStart(2,"0")}`;}
async function request<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,signal:AbortSignal.timeout(35000)});const data=await response.json() as T&{error?:string};if(!response.ok)throw new Error(data.error||"请求失败，请稍后重试");return data;}
type Info={sources:{id:string;name:string;type:string}[];ai:boolean;error:string|null};

export function CinemaApp(){
  const [query,setQuery]=useState("");const [submitted,setSubmitted]=useState("");const [aiMode,setAiMode]=useState(false);const [view,setView]=useState("explore");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [aiMessage,setAiMessage]=useState("");
  const [result,setResult]=useState<SearchResult>({movies:demoMovies,sources:[]});const [info,setInfo]=useState<Info>({sources:[{id:"demo",name:"公开授权预告",type:"builtin"}],ai:false,error:null});
  const [favorites,setFavorites]=useState<Movie[]>([]);const [history,setHistory]=useState<WatchRecord[]>([]);const [catalog,setCatalog]=useState<Movie[]>([]);const [settings,setSettings]=useState(false);const [selected,setSelected]=useState<Movie>();const [opening,setOpening]=useState("");const [sourceExpanded,setSourceExpanded]=useState(false);
  const requestId=useRef(0);const importedRef=useRef(catalog);importedRef.current=catalog;const historyRef=useRef(history);historyRef.current=history;const fileRef=useRef<HTMLInputElement>(null);

  useEffect(()=>{
    const savedFavorites=load<unknown>(keys.favorites,[]);const savedHistory=load<unknown>(keys.history,[]);const savedCatalog=load<unknown>(keys.catalog,[]);
    if(Array.isArray(savedFavorites))setFavorites(savedFavorites.filter(item=>item?.id&&typeof item.title==="string"&&Array.isArray(item.lines)).slice(0,100));
    if(Array.isArray(savedHistory))setHistory(savedHistory.filter(item=>item?.movie?.id&&Array.isArray(item.movie.lines)&&typeof item.seconds==="number").slice(0,50));
    if(Array.isArray(savedCatalog))setCatalog(savedCatalog.filter(item=>item?.id&&Array.isArray(item.lines)).slice(0,1000));
    let active=true;
    request<Info>("/api/sources").then(data=>{if(active)setInfo(data);}).catch(()=>{if(active)setError("无法读取片源状态，请刷新页面重试");});
    request<SearchResult>("/api/search").then(data=>{if(active)setResult(data);}).catch(()=>{if(active)setError("服务器暂时不可用，仍可播放内置公开预告");});
    return()=>{active=false;};
  },[]);
  const search=useCallback(async(value:string,useAi:boolean)=>{
    const q=value.trim();if(q.length>(useAi?500:100)){toast.error(useAi?"描述最多 500 个字符":"片名最多 100 个字符");return;}
    const id=++requestId.current;setQuery(value);setSubmitted(q);setView("explore");setBusy(true);setError("");setAiMessage("");setResult({movies:[],sources:[]});
    try{
      if(useAi&&q){const data=await request<SearchResult&{configured:boolean;message:string;keywords?:string[]}>("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:q})});if(id!==requestId.current)return;setAiMessage(data.message);if(!data.configured){setSettings(true);return;}const local=importedRef.current.filter(movie=>data.keywords?.some(keyword=>matches(movie,keyword)));setResult({...data,movies:mergeMovies([...data.movies,...local])});}
      else{const data=await request<SearchResult>(`/api/search?q=${encodeURIComponent(q)}`);if(id!==requestId.current)return;setResult(data);}
    }catch(error){if(id===requestId.current)setError(error instanceof Error?error.message:"搜索失败，请重试");}finally{if(id===requestId.current)setBusy(false);}
  },[]);
  const saveProgress=useCallback((record:WatchRecord)=>{const next=[record,...historyRef.current.filter(item=>item.movie.id!==record.movie.id)].slice(0,50);historyRef.current=next;setHistory(next);persist(keys.history,next);},[]);
  function favorite(movie:Movie){const exists=favorites.some(item=>item.id===movie.id);const next=exists?favorites.filter(item=>item.id!==movie.id):[movie,...favorites].slice(0,100);setFavorites(next);persist(keys.favorites,next);toast.success(exists?"已取消收藏":"已收藏到本设备");}
  async function openMovie(movie:Movie){if(opening)return;setOpening(movie.id);try{let full=movie;if(!full.lines.length&&!full.id.startsWith("local:"))full=await request<Movie>(`/api/movie?id=${encodeURIComponent(movie.id)}`);if(!full.lines.length){toast.error("该来源还没有提供播放地址");return;}setSelected(full);}catch(error){toast.error(error instanceof Error?error.message:"无法读取剧集");}finally{setOpening("");}}
  async function importCatalog(file?:File){if(!file)return;try{if(file.size>2000000)throw new Error("片库文件不能超过 2 MB");const parsed=parseCatalog(JSON.parse(await file.text()),"local","我的片库");if(!parsed.length)throw new Error("文件中没有有效影片，请检查 id、title 和播放地址");const next=mergeMovies([...parsed,...catalog]).slice(0,1000);setCatalog(next);persist(keys.catalog,next);toast.success(`已导入 ${parsed.length} 部影片`);}catch(error){toast.error(error instanceof Error?error.message:"导入失败，请检查 JSON 文件");}finally{if(fileRef.current)fileRef.current.value="";}}
  function removeHistory(id:string){const next=history.filter(item=>item.movie.id!==id);historyRef.current=next;setHistory(next);persist(keys.history,next);}
  const movies=view==="favorites"?favorites:view==="history"?history.map(item=>item.movie):mergeMovies([...result.movies,...(!aiMode||!submitted?catalog.filter(movie=>matches(movie,submitted)):[])]);
  const sourceStatuses:SourceStatus[]=[...result.sources,...(catalog.length?[{id:"local",name:"我的片库",state:"ok" as const,count:catalog.length}]:[])];

  useEffect(()=>{
    const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;
    const lifetime=new AbortController();Promise.resolve(context.registerTool({name:"search_movies",title:"搜索家庭片库",description:"按片名搜索并更新当前页面。只返回实际配置片库的结果。",inputSchema:{type:"object",properties:{query:{type:"string",maxLength:100}},required:["query"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const value=(input as {query?:unknown})?.query;if(typeof value!=="string"||value.length>100)throw new Error("query 必须为不超过 100 字的字符串");setAiMode(false);await search(value,false);const data=await request<SearchResult>(`/api/search?q=${encodeURIComponent(value.trim())}`);return {query:value,movies:mergeMovies([...data.movies,...importedRef.current.filter(movie=>matches(movie,value))]).map(({id,title,source})=>({id,title,source})),sources:data.sources};}},{signal:lifetime.signal})).catch(()=>{});return()=>lifetime.abort();
  },[search]);

  return <div className="cinema-shell"><header className="masthead"><a href="/" className="brand"><span className="brand-icon"><Film size={22}/></span><span>家映<small>JIAYING CINEMA</small></span></a><div className="header-right"><span className="private-label">家庭片库</span><Button variant="ghost" onClick={()=>setSettings(true)}><SlidersHorizontal size={17}/>片源设置</Button></div></header>
  <main className="main-content"><section className="search-section"><div className="eyebrow">找一部好片，留一点时间给自己</div><div className="search-title"><h1>今晚想看什么？</h1><label className="ai-switch"><Switch checked={aiMode} onCheckedChange={setAiMode} aria-label="AI 搜剧"/><Sparkles size={16}/>AI 搜剧</label></div><form className="search-box" onSubmit={event=>{event.preventDefault();void search(query,aiMode);}}><Search size={22}/><input aria-label="影视搜索" value={query} onChange={event=>setQuery(event.target.value)} maxLength={aiMode?500:100} placeholder={aiMode?"例如：想看轻松一点、有动物主角的动画":"输入片名、演员或类型"}/><Button type="submit" className="search-submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:"搜索"}</Button></form><div className="search-hints"><span>试着搜</span>{["大雄兔","奇幻","动画"].map(value=><button key={value} onClick={()=>{setAiMode(false);void search(value,false);}}>{value}</button>)}<span className="source-count">{info.sources.length+Number(catalog.length>0)} 个片源{!info.ai&&aiMode?" · AI 尚未接入":""}</span></div></section>
  <Tabs value={view} onValueChange={setView} className="library-tabs"><div className="library-toolbar"><TabsList variant="line"><TabsTrigger value="explore"><Film/>片库</TabsTrigger><TabsTrigger value="history"><History/>继续观看{history.length>0&&<span className="tab-count">{history.length}</span>}</TabsTrigger><TabsTrigger value="favorites"><Bookmark/>收藏{favorites.length>0&&<span className="tab-count">{favorites.length}</span>}</TabsTrigger></TabsList><button className="source-summary" onClick={()=>setSourceExpanded(value=>!value)} aria-expanded={sourceExpanded}><Database size={15}/>片源状态</button></div>
  {sourceExpanded&&<div className="source-status-list">{sourceStatuses.map(source=><div className={source.state==="error"?"source-error":""} key={source.id}><span>{source.name}</span><span>{source.state==="error"?source.message:`${source.count??0} 部结果`}{source.elapsedMs!==undefined&&` · ${source.elapsedMs} ms`}</span></div>)}<p>连接成功表示接口可访问，播放状态以播放器实际加载结果为准。</p></div>}
  <TabsContent value={view}>
  {error&&view==="explore"&&<div className="error-notice" role="alert"><CircleAlert size={18}/><span>{error}</span><Button variant="ghost" onClick={()=>void search(query,aiMode)}>重试</Button></div>}
  {aiMessage&&view==="explore"&&<div className="ai-notice" role="status"><Sparkles size={18}/><p>{aiMessage}</p></div>}
  <div className="section-heading"><h2>{view==="favorites"?"我的收藏":view==="history"?"接着上次看":submitted?`“${submitted}” 的搜索结果`:"从片库开始"}</h2><span>{view==="explore"&&!info.sources.some(source=>source.id!=="demo")&&!catalog.length?"公开授权预告 · 完整剧集需接入片源":`${movies.length} 部影片 · 记录保存在本设备`}</span></div>
  {busy&&view==="explore"?<div className="movie-grid" aria-label="正在搜索">{[0,1].map(id=><div key={id}><Skeleton className="loading-cover"/><Skeleton className="loading-title"/></div>)}</div>:movies.length?<div className="movie-grid">{movies.map(movie=>{const watched=history.find(item=>item.movie.id===movie.id);const saved=favorites.some(item=>item.id===movie.id);return <article className="movie-card" key={movie.id}><button className="movie-image" onClick={()=>void openMovie(movie)} aria-label={`播放${movie.title}`} disabled={Boolean(opening)}>{movie.poster?<img src={movie.poster} alt={movie.title} loading="lazy" referrerPolicy="no-referrer" onError={event=>{event.currentTarget.style.display="none";}}/>:<div className="poster-fallback"><Film size={40}/><span>{movie.title}</span></div>}<span className="movie-type">{movie.tags.includes("预告")?"预告片":movie.tags[0]||"影视"}</span><span className="play-bubble">{opening===movie.id?<LoaderCircle className="spin" size={20}/>:<Play size={20}/>}</span>{view==="history"&&watched&&<span className="watch-time">看到 {time(watched.seconds)}</span>}</button><div className="movie-caption"><h3>{movie.title}<small>{movie.originalTitle}</small></h3><div className="card-actions"><span>{movie.year}</span><Button variant="ghost" size="icon" aria-label={`${saved?"取消收藏":"收藏"}${movie.title}`} onClick={()=>favorite(movie)}>{saved?<BookmarkCheck className="saved" size={18}/>:<Bookmark size={18}/>}</Button>{view==="history"&&<Button variant="ghost" size="icon" aria-label={`移除${movie.title}观看记录`} onClick={()=>removeHistory(movie.id)}><X size={16}/></Button>}</div></div><p className="card-description">{movie.description}</p><div className="card-meta"><span>{movie.source}</span><span>{movie.lines.length?`${movie.lines.length} 条线路`:"获取剧集"}</span></div></article>;})}</div>:<Empty className="library-empty"><EmptyTitle>{view==="history"?"还没有观看记录":view==="favorites"?"还没有收藏影片":"暂时没有匹配结果"}</EmptyTitle><EmptyDescription>{view==="explore"?"换个片名试试，或在片源设置中导入自己的片库。":view==="history"?"播放影片后，这里会保存你看到的位置。":"点影片旁的收藏按钮，留着下次看。"}</EmptyDescription><Button variant="secondary" onClick={()=>{setAiMode(false);void search("",false);}}>回到片库</Button></Empty>}
  </TabsContent></Tabs><footer>家映 · 你的家庭观影空间<span>影片来自已配置片源，AI 仅帮助检索。</span></footer></main>
  <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="settings-dialog"><DialogTitle>片源与 AI</DialogTitle><DialogDescription>接入自己的片库，或查看已配置的搜索来源。</DialogDescription><div className="settings-section"><h3>当前片源</h3>{info.sources.map(source=><div className="configured-source" key={source.id}><Database size={18}/><div><strong>{source.name}</strong><small>{source.type==="builtin"?"内置公开预告 · 2 部":source.type==="catalog"?"JSON 片库接口":"影视采集接口"}</small></div><span>已配置</span></div>)}{info.error&&<p className="error-text">{info.error}</p>}</div><div className="settings-section"><h3>我的片库 <span>{catalog.length} 部</span></h3><p>导入包含影片和播放地址的 JSON 文件，保存到当前设备。适合自有视频或已授权片源。</p><input hidden ref={fileRef} type="file" accept=".json,application/json" onChange={event=>void importCatalog(event.target.files?.[0])}/><div className="settings-buttons"><Button variant="secondary" onClick={()=>fileRef.current?.click()}><Upload/>导入片库</Button><Button asChild variant="ghost"><a href="/catalog-example.json" download>下载格式示例</a></Button>{catalog.length>0&&<Button variant="ghost" onClick={()=>{setCatalog([]);persist(keys.catalog,[]);toast.success("已移除本设备导入的片库");}}>移除导入片库</Button>}</div></div><div className="settings-section"><h3>AI 搜剧 <span>{info.ai?"已接入":"尚未接入"}</span></h3><p>{info.ai?"描述想看的故事，AI 会生成检索词，再查询实际片库。": "需要配置 AI 服务地址、模型和密钥后启用。当前可以使用片名搜索。"}</p></div><details className="setup-details"><summary>服务器接入说明</summary><p>服务端支持 JSON 片库和 MacCMS 格式接口。在服务器设置 CINEMA_SOURCES，最多 6 个来源。AI 需设置 AI_BASE_URL、AI_MODEL、AI_API_KEY；密钥只留在服务器。</p><p>来源连接成功不代表每部影片可播放。受登录、访问限制或播放授权保护的地址，需要相应平台的可用播放接入。</p><a href="/接入说明.txt" target="_blank" rel="noopener noreferrer">查看配置说明</a></details><p className="device-note">收藏、观看进度和导入片库保存在当前浏览器，暂不跨设备同步。</p></DialogContent></Dialog>
  {selected&&<MoviePlayer key={selected.id} movie={selected} record={history.find(item=>item.movie.id===selected.id)} favorite={favorites.some(item=>item.id===selected.id)} onClose={()=>setSelected(undefined)} onFavorite={()=>favorite(selected)} onProgress={saveProgress}/>}<Toaster theme="dark"/>
  </div>;
}
